apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: containerapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: containerapp
    spec:
      containers:
      - name: containerapp
        image: loginServerFromPoint6Task3/containerapp
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: <SECRET_NAME>
